server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 600
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    #Tomcat超时时间
    connection-timeout: 60s
spring:
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
        keep-alive: 60s
        max-size: 8
        queue-capacity: 8
    scheduling:
      shutdown:
        await-termination: false
  datasource:
    username:
    password:
    url: jdbc:sqlite:./db/data.db3
    driver-class-name: org.sqlite.JDBC
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 30000
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.twg.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
#Bot插件列表(有序) 如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
shiro:
  plugin-list:
    - com.twg.bot.plugin.FunctionOnOffPlugin
    - com.twg.bot.group.plugin.JoinGroupVerifyCodePlugin
    - com.twg.bot.warframe.plugin.WarframePlugin
    - com.twg.bot.imagetogif.plugin.GifImagePlugin